version: 0.2

env:
  parameter-store:
    settings_secret_userPoolID: "/WikiProject/stg/settings_secret/userPoolID"
    settings_secret_clientID: "/WikiProject/stg/settings_secret/clientID"
    settings_secret_MAPPING_PATH: "/WikiProject/stg/settings_secret/MAPPING_PATH"
    settings_secret_DEBUG: "/WikiProject/stg/settings_secret/DEBUG"
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt -t build/external/python/lib/python3.12/site-packages
  build:
    commands:
      - echo $settings_secret > build/project/python/lib/python3.12/site-packages/project/settings_secret.py
      - cat build/project/python/lib/python3.12/site-packages/project/settings_secret.py
      - python3 ./gen_settings_secret.py -u $settings_secret_userPoolID -c $settings_secret_clientID -m $settings_secret_MAPPING_PATH -d $settings_secret_DEBUG
      - ls /usr/local/bin
      - had-admin.py -h
      # - had-admin.py -Y settings.json -A add.yaml -H settings.json
      # - |
      #   if had-admin.py -x settings.json > /dev/null 2>&1; then
      #     had-admin.py -u settings.json
      #   else
      #     had-admin.py -c settings.json
      #   fi
      # - echo "Build completed on `date`"
